### ISSUE TITLE
Add a `row_factory` argument

### ISSUE THREAD

**Issue by IvanKirpichnikov** [qaspen-python/psqlpy#47]
Add a `row_factory` argument to the ResultQuery.result and SingleQueryResult.result methods

You pass your function there, to which strings will fly. The function will process them. In turn, the result will be collected in a list and returned. 

Example code
```py
def my_row_factory(rows: list[str], data: list[Any]):
    return tuple(data)

data = query_result.result(row_factory=my_row_factory)
assert data == [(1, 'aaa', 34.13)]
```

**Comment by chandr-andr** [comment]
Thanks for the new feature request!
We'll look into it as soon as possible

**Comment by chandr-andr** [comment]
@IvanKirpichnikov You can find `row_factory` as a method in `QueryResult`.

**Comment by chandr-andr** [comment]
As requested feature was developed, closing this issue.
If there are any problems, don't hesitate to reopen it.
